// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/watcher/v1/watch.proto

package com.google.watcher.v1;

/**
 * <pre>
 * A Change indicates the most recent state of an element.
 * </pre>
 *
 * Protobuf type {@code google.watcher.v1.Change}
 */
public final class Change extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.watcher.v1.Change)
    ChangeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Change.newBuilder() to construct.
  private Change(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Change() {
    element_ = "";
    state_ = 0;
    resumeMarker_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Change();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.watcher.v1.WatchProto.internal_static_google_watcher_v1_Change_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.watcher.v1.WatchProto.internal_static_google_watcher_v1_Change_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.watcher.v1.Change.class, com.google.watcher.v1.Change.Builder.class);
  }

  /**
   * <pre>
   * A reported value can be in one of the following states:
   * </pre>
   *
   * Protobuf enum {@code google.watcher.v1.Change.State}
   */
  public enum State
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * The element exists and its full value is included in data.
     * </pre>
     *
     * <code>EXISTS = 0;</code>
     */
    EXISTS(0),
    /**
     * <pre>
     * The element does not exist.
     * </pre>
     *
     * <code>DOES_NOT_EXIST = 1;</code>
     */
    DOES_NOT_EXIST(1),
    /**
     * <pre>
     * Element may or may not exist. Used only for initial state delivery when
     * the client is not interested in fetching the initial state. See the
     * "Initial State" section above.
     * </pre>
     *
     * <code>INITIAL_STATE_SKIPPED = 2;</code>
     */
    INITIAL_STATE_SKIPPED(2),
    /**
     * <pre>
     * The element may exist, but some error has occurred. More information is
     * available in the data field - the value is a serialized Status
     * proto (from [google.rpc.Status][])
     * </pre>
     *
     * <code>ERROR = 3;</code>
     */
    ERROR(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * The element exists and its full value is included in data.
     * </pre>
     *
     * <code>EXISTS = 0;</code>
     */
    public static final int EXISTS_VALUE = 0;
    /**
     * <pre>
     * The element does not exist.
     * </pre>
     *
     * <code>DOES_NOT_EXIST = 1;</code>
     */
    public static final int DOES_NOT_EXIST_VALUE = 1;
    /**
     * <pre>
     * Element may or may not exist. Used only for initial state delivery when
     * the client is not interested in fetching the initial state. See the
     * "Initial State" section above.
     * </pre>
     *
     * <code>INITIAL_STATE_SKIPPED = 2;</code>
     */
    public static final int INITIAL_STATE_SKIPPED_VALUE = 2;
    /**
     * <pre>
     * The element may exist, but some error has occurred. More information is
     * available in the data field - the value is a serialized Status
     * proto (from [google.rpc.Status][])
     * </pre>
     *
     * <code>ERROR = 3;</code>
     */
    public static final int ERROR_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static State valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static State forNumber(int value) {
      switch (value) {
        case 0: return EXISTS;
        case 1: return DOES_NOT_EXIST;
        case 2: return INITIAL_STATE_SKIPPED;
        case 3: return ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<State>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        State> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<State>() {
            public State findValueByNumber(int number) {
              return State.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.watcher.v1.Change.getDescriptor().getEnumTypes().get(0);
    }

    private static final State[] VALUES = values();

    public static State valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private State(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:google.watcher.v1.Change.State)
  }

  public static final int ELEMENT_FIELD_NUMBER = 1;
  private volatile java.lang.Object element_;
  /**
   * <pre>
   * Name of the element, interpreted relative to the entity's actual
   * name. "" refers to the entity itself. The element name is a valid
   * UTF-8 string.
   * </pre>
   *
   * <code>string element = 1;</code>
   * @return The element.
   */
  @java.lang.Override
  public java.lang.String getElement() {
    java.lang.Object ref = element_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      element_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the element, interpreted relative to the entity's actual
   * name. "" refers to the entity itself. The element name is a valid
   * UTF-8 string.
   * </pre>
   *
   * <code>string element = 1;</code>
   * @return The bytes for element.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getElementBytes() {
    java.lang.Object ref = element_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      element_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATE_FIELD_NUMBER = 2;
  private int state_;
  /**
   * <pre>
   * The state of the `element`.
   * </pre>
   *
   * <code>.google.watcher.v1.Change.State state = 2;</code>
   * @return The enum numeric value on the wire for state.
   */
  @java.lang.Override public int getStateValue() {
    return state_;
  }
  /**
   * <pre>
   * The state of the `element`.
   * </pre>
   *
   * <code>.google.watcher.v1.Change.State state = 2;</code>
   * @return The state.
   */
  @java.lang.Override public com.google.watcher.v1.Change.State getState() {
    @SuppressWarnings("deprecation")
    com.google.watcher.v1.Change.State result = com.google.watcher.v1.Change.State.valueOf(state_);
    return result == null ? com.google.watcher.v1.Change.State.UNRECOGNIZED : result;
  }

  public static final int DATA_FIELD_NUMBER = 6;
  private com.google.protobuf.Any data_;
  /**
   * <pre>
   * The actual change data. This field is present only when `state() == EXISTS`
   * or `state() == ERROR`. Please see [google.protobuf.Any][google.protobuf.Any] about how to use
   * the Any type.
   * </pre>
   *
   * <code>.google.protobuf.Any data = 6;</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <pre>
   * The actual change data. This field is present only when `state() == EXISTS`
   * or `state() == ERROR`. Please see [google.protobuf.Any][google.protobuf.Any] about how to use
   * the Any type.
   * </pre>
   *
   * <code>.google.protobuf.Any data = 6;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.Any getData() {
    return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
  }
  /**
   * <pre>
   * The actual change data. This field is present only when `state() == EXISTS`
   * or `state() == ERROR`. Please see [google.protobuf.Any][google.protobuf.Any] about how to use
   * the Any type.
   * </pre>
   *
   * <code>.google.protobuf.Any data = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
    return getData();
  }

  public static final int RESUME_MARKER_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString resumeMarker_;
  /**
   * <pre>
   * If present, provides a compact representation of all the messages that have
   * been received by the caller for the given entity, e.g., it could be a
   * sequence number or a multi-part timestamp/version vector. This marker can
   * be provided in the Request message, allowing the caller to resume the stream
   * watching at a specific point without fetching the initial state.
   * </pre>
   *
   * <code>bytes resume_marker = 4;</code>
   * @return The resumeMarker.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getResumeMarker() {
    return resumeMarker_;
  }

  public static final int CONTINUED_FIELD_NUMBER = 5;
  private boolean continued_;
  /**
   * <pre>
   * If true, this Change is followed by more Changes that are in the same group
   * as this Change.
   * </pre>
   *
   * <code>bool continued = 5;</code>
   * @return The continued.
   */
  @java.lang.Override
  public boolean getContinued() {
    return continued_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(element_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, element_);
    }
    if (state_ != com.google.watcher.v1.Change.State.EXISTS.getNumber()) {
      output.writeEnum(2, state_);
    }
    if (!resumeMarker_.isEmpty()) {
      output.writeBytes(4, resumeMarker_);
    }
    if (continued_ != false) {
      output.writeBool(5, continued_);
    }
    if (data_ != null) {
      output.writeMessage(6, getData());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(element_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, element_);
    }
    if (state_ != com.google.watcher.v1.Change.State.EXISTS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, state_);
    }
    if (!resumeMarker_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, resumeMarker_);
    }
    if (continued_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, continued_);
    }
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getData());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.watcher.v1.Change)) {
      return super.equals(obj);
    }
    com.google.watcher.v1.Change other = (com.google.watcher.v1.Change) obj;

    if (!getElement()
        .equals(other.getElement())) return false;
    if (state_ != other.state_) return false;
    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (!getResumeMarker()
        .equals(other.getResumeMarker())) return false;
    if (getContinued()
        != other.getContinued()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ELEMENT_FIELD_NUMBER;
    hash = (53 * hash) + getElement().hashCode();
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + state_;
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (37 * hash) + RESUME_MARKER_FIELD_NUMBER;
    hash = (53 * hash) + getResumeMarker().hashCode();
    hash = (37 * hash) + CONTINUED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getContinued());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.watcher.v1.Change parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.watcher.v1.Change parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.watcher.v1.Change parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.watcher.v1.Change parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.watcher.v1.Change parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.watcher.v1.Change parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.watcher.v1.Change parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.watcher.v1.Change parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.watcher.v1.Change parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.watcher.v1.Change parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.watcher.v1.Change parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.watcher.v1.Change parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.watcher.v1.Change prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A Change indicates the most recent state of an element.
   * </pre>
   *
   * Protobuf type {@code google.watcher.v1.Change}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.watcher.v1.Change)
      com.google.watcher.v1.ChangeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.watcher.v1.WatchProto.internal_static_google_watcher_v1_Change_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.watcher.v1.WatchProto.internal_static_google_watcher_v1_Change_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.watcher.v1.Change.class, com.google.watcher.v1.Change.Builder.class);
    }

    // Construct using com.google.watcher.v1.Change.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      element_ = "";

      state_ = 0;

      if (dataBuilder_ == null) {
        data_ = null;
      } else {
        data_ = null;
        dataBuilder_ = null;
      }
      resumeMarker_ = com.google.protobuf.ByteString.EMPTY;

      continued_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.watcher.v1.WatchProto.internal_static_google_watcher_v1_Change_descriptor;
    }

    @java.lang.Override
    public com.google.watcher.v1.Change getDefaultInstanceForType() {
      return com.google.watcher.v1.Change.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.watcher.v1.Change build() {
      com.google.watcher.v1.Change result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.watcher.v1.Change buildPartial() {
      com.google.watcher.v1.Change result = new com.google.watcher.v1.Change(this);
      result.element_ = element_;
      result.state_ = state_;
      if (dataBuilder_ == null) {
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      result.resumeMarker_ = resumeMarker_;
      result.continued_ = continued_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.watcher.v1.Change) {
        return mergeFrom((com.google.watcher.v1.Change)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.watcher.v1.Change other) {
      if (other == com.google.watcher.v1.Change.getDefaultInstance()) return this;
      if (!other.getElement().isEmpty()) {
        element_ = other.element_;
        onChanged();
      }
      if (other.state_ != 0) {
        setStateValue(other.getStateValue());
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      if (other.getResumeMarker() != com.google.protobuf.ByteString.EMPTY) {
        setResumeMarker(other.getResumeMarker());
      }
      if (other.getContinued() != false) {
        setContinued(other.getContinued());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              element_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 16: {
              state_ = input.readEnum();

              break;
            } // case 16
            case 34: {
              resumeMarker_ = input.readBytes();

              break;
            } // case 34
            case 40: {
              continued_ = input.readBool();

              break;
            } // case 40
            case 50: {
              input.readMessage(
                  getDataFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object element_ = "";
    /**
     * <pre>
     * Name of the element, interpreted relative to the entity's actual
     * name. "" refers to the entity itself. The element name is a valid
     * UTF-8 string.
     * </pre>
     *
     * <code>string element = 1;</code>
     * @return The element.
     */
    public java.lang.String getElement() {
      java.lang.Object ref = element_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        element_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the element, interpreted relative to the entity's actual
     * name. "" refers to the entity itself. The element name is a valid
     * UTF-8 string.
     * </pre>
     *
     * <code>string element = 1;</code>
     * @return The bytes for element.
     */
    public com.google.protobuf.ByteString
        getElementBytes() {
      java.lang.Object ref = element_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        element_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the element, interpreted relative to the entity's actual
     * name. "" refers to the entity itself. The element name is a valid
     * UTF-8 string.
     * </pre>
     *
     * <code>string element = 1;</code>
     * @param value The element to set.
     * @return This builder for chaining.
     */
    public Builder setElement(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      element_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the element, interpreted relative to the entity's actual
     * name. "" refers to the entity itself. The element name is a valid
     * UTF-8 string.
     * </pre>
     *
     * <code>string element = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearElement() {
      
      element_ = getDefaultInstance().getElement();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the element, interpreted relative to the entity's actual
     * name. "" refers to the entity itself. The element name is a valid
     * UTF-8 string.
     * </pre>
     *
     * <code>string element = 1;</code>
     * @param value The bytes for element to set.
     * @return This builder for chaining.
     */
    public Builder setElementBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      element_ = value;
      onChanged();
      return this;
    }

    private int state_ = 0;
    /**
     * <pre>
     * The state of the `element`.
     * </pre>
     *
     * <code>.google.watcher.v1.Change.State state = 2;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <pre>
     * The state of the `element`.
     * </pre>
     *
     * <code>.google.watcher.v1.Change.State state = 2;</code>
     * @param value The enum numeric value on the wire for state to set.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      
      state_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The state of the `element`.
     * </pre>
     *
     * <code>.google.watcher.v1.Change.State state = 2;</code>
     * @return The state.
     */
    @java.lang.Override
    public com.google.watcher.v1.Change.State getState() {
      @SuppressWarnings("deprecation")
      com.google.watcher.v1.Change.State result = com.google.watcher.v1.Change.State.valueOf(state_);
      return result == null ? com.google.watcher.v1.Change.State.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The state of the `element`.
     * </pre>
     *
     * <code>.google.watcher.v1.Change.State state = 2;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(com.google.watcher.v1.Change.State value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The state of the `element`.
     * </pre>
     *
     * <code>.google.watcher.v1.Change.State state = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      
      state_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Any data_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> dataBuilder_;
    /**
     * <pre>
     * The actual change data. This field is present only when `state() == EXISTS`
     * or `state() == ERROR`. Please see [google.protobuf.Any][google.protobuf.Any] about how to use
     * the Any type.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 6;</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return dataBuilder_ != null || data_ != null;
    }
    /**
     * <pre>
     * The actual change data. This field is present only when `state() == EXISTS`
     * or `state() == ERROR`. Please see [google.protobuf.Any][google.protobuf.Any] about how to use
     * the Any type.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 6;</code>
     * @return The data.
     */
    public com.google.protobuf.Any getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The actual change data. This field is present only when `state() == EXISTS`
     * or `state() == ERROR`. Please see [google.protobuf.Any][google.protobuf.Any] about how to use
     * the Any type.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 6;</code>
     */
    public Builder setData(com.google.protobuf.Any value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The actual change data. This field is present only when `state() == EXISTS`
     * or `state() == ERROR`. Please see [google.protobuf.Any][google.protobuf.Any] about how to use
     * the Any type.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 6;</code>
     */
    public Builder setData(
        com.google.protobuf.Any.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The actual change data. This field is present only when `state() == EXISTS`
     * or `state() == ERROR`. Please see [google.protobuf.Any][google.protobuf.Any] about how to use
     * the Any type.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 6;</code>
     */
    public Builder mergeData(com.google.protobuf.Any value) {
      if (dataBuilder_ == null) {
        if (data_ != null) {
          data_ =
            com.google.protobuf.Any.newBuilder(data_).mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        dataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The actual change data. This field is present only when `state() == EXISTS`
     * or `state() == ERROR`. Please see [google.protobuf.Any][google.protobuf.Any] about how to use
     * the Any type.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 6;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = null;
        onChanged();
      } else {
        data_ = null;
        dataBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The actual change data. This field is present only when `state() == EXISTS`
     * or `state() == ERROR`. Please see [google.protobuf.Any][google.protobuf.Any] about how to use
     * the Any type.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 6;</code>
     */
    public com.google.protobuf.Any.Builder getDataBuilder() {
      
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The actual change data. This field is present only when `state() == EXISTS`
     * or `state() == ERROR`. Please see [google.protobuf.Any][google.protobuf.Any] about how to use
     * the Any type.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 6;</code>
     */
    public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : data_;
      }
    }
    /**
     * <pre>
     * The actual change data. This field is present only when `state() == EXISTS`
     * or `state() == ERROR`. Please see [google.protobuf.Any][google.protobuf.Any] about how to use
     * the Any type.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    private com.google.protobuf.ByteString resumeMarker_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * If present, provides a compact representation of all the messages that have
     * been received by the caller for the given entity, e.g., it could be a
     * sequence number or a multi-part timestamp/version vector. This marker can
     * be provided in the Request message, allowing the caller to resume the stream
     * watching at a specific point without fetching the initial state.
     * </pre>
     *
     * <code>bytes resume_marker = 4;</code>
     * @return The resumeMarker.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getResumeMarker() {
      return resumeMarker_;
    }
    /**
     * <pre>
     * If present, provides a compact representation of all the messages that have
     * been received by the caller for the given entity, e.g., it could be a
     * sequence number or a multi-part timestamp/version vector. This marker can
     * be provided in the Request message, allowing the caller to resume the stream
     * watching at a specific point without fetching the initial state.
     * </pre>
     *
     * <code>bytes resume_marker = 4;</code>
     * @param value The resumeMarker to set.
     * @return This builder for chaining.
     */
    public Builder setResumeMarker(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resumeMarker_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If present, provides a compact representation of all the messages that have
     * been received by the caller for the given entity, e.g., it could be a
     * sequence number or a multi-part timestamp/version vector. This marker can
     * be provided in the Request message, allowing the caller to resume the stream
     * watching at a specific point without fetching the initial state.
     * </pre>
     *
     * <code>bytes resume_marker = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearResumeMarker() {
      
      resumeMarker_ = getDefaultInstance().getResumeMarker();
      onChanged();
      return this;
    }

    private boolean continued_ ;
    /**
     * <pre>
     * If true, this Change is followed by more Changes that are in the same group
     * as this Change.
     * </pre>
     *
     * <code>bool continued = 5;</code>
     * @return The continued.
     */
    @java.lang.Override
    public boolean getContinued() {
      return continued_;
    }
    /**
     * <pre>
     * If true, this Change is followed by more Changes that are in the same group
     * as this Change.
     * </pre>
     *
     * <code>bool continued = 5;</code>
     * @param value The continued to set.
     * @return This builder for chaining.
     */
    public Builder setContinued(boolean value) {
      
      continued_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If true, this Change is followed by more Changes that are in the same group
     * as this Change.
     * </pre>
     *
     * <code>bool continued = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearContinued() {
      
      continued_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.watcher.v1.Change)
  }

  // @@protoc_insertion_point(class_scope:google.watcher.v1.Change)
  private static final com.google.watcher.v1.Change DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.watcher.v1.Change();
  }

  public static com.google.watcher.v1.Change getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Change>
      PARSER = new com.google.protobuf.AbstractParser<Change>() {
    @java.lang.Override
    public Change parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Change> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Change> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.watcher.v1.Change getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

