// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/remoteexecution/v1test/remote_execution.proto

package com.google.devtools.remoteexecution.v1test;

public interface ExecuteOperationMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.devtools.remoteexecution.v1test.ExecuteOperationMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage stage = 1;</code>
   * @return The enum numeric value on the wire for stage.
   */
  int getStageValue();
  /**
   * <code>.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage stage = 1;</code>
   * @return The stage.
   */
  com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage getStage();

  /**
   * <pre>
   * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
   * being executed.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
   * @return Whether the actionDigest field is set.
   */
  boolean hasActionDigest();
  /**
   * <pre>
   * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
   * being executed.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
   * @return The actionDigest.
   */
  com.google.devtools.remoteexecution.v1test.Digest getActionDigest();
  /**
   * <pre>
   * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
   * being executed.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
   */
  com.google.devtools.remoteexecution.v1test.DigestOrBuilder getActionDigestOrBuilder();

  /**
   * <pre>
   * If set, the client can use this name with
   * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
   * standard output.
   * </pre>
   *
   * <code>string stdout_stream_name = 3;</code>
   * @return The stdoutStreamName.
   */
  java.lang.String getStdoutStreamName();
  /**
   * <pre>
   * If set, the client can use this name with
   * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
   * standard output.
   * </pre>
   *
   * <code>string stdout_stream_name = 3;</code>
   * @return The bytes for stdoutStreamName.
   */
  com.google.protobuf.ByteString
      getStdoutStreamNameBytes();

  /**
   * <pre>
   * If set, the client can use this name with
   * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
   * standard error.
   * </pre>
   *
   * <code>string stderr_stream_name = 4;</code>
   * @return The stderrStreamName.
   */
  java.lang.String getStderrStreamName();
  /**
   * <pre>
   * If set, the client can use this name with
   * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
   * standard error.
   * </pre>
   *
   * <code>string stderr_stream_name = 4;</code>
   * @return The bytes for stderrStreamName.
   */
  com.google.protobuf.ByteString
      getStderrStreamNameBytes();
}
