// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/remoteexecution/v1test/remote_execution.proto

package com.google.devtools.remoteexecution.v1test;

/**
 * <pre>
 * Metadata about an ongoing
 * [execution][google.devtools.remoteexecution.v1test.Execution.Execute], which
 * will be contained in the [metadata
 * field][google.longrunning.Operation.response] of the
 * [Operation][google.longrunning.Operation].
 * </pre>
 *
 * Protobuf type {@code google.devtools.remoteexecution.v1test.ExecuteOperationMetadata}
 */
public final class ExecuteOperationMetadata extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.devtools.remoteexecution.v1test.ExecuteOperationMetadata)
    ExecuteOperationMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecuteOperationMetadata.newBuilder() to construct.
  private ExecuteOperationMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecuteOperationMetadata() {
    stage_ = 0;
    stdoutStreamName_ = "";
    stderrStreamName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExecuteOperationMetadata();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_ExecuteOperationMetadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_ExecuteOperationMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.class, com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Builder.class);
  }

  /**
   * <pre>
   * The current stage of execution.
   * </pre>
   *
   * Protobuf enum {@code google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage}
   */
  public enum Stage
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <pre>
     * Checking the result against the cache.
     * </pre>
     *
     * <code>CACHE_CHECK = 1;</code>
     */
    CACHE_CHECK(1),
    /**
     * <pre>
     * Currently idle, awaiting a free machine to execute.
     * </pre>
     *
     * <code>QUEUED = 2;</code>
     */
    QUEUED(2),
    /**
     * <pre>
     * Currently being executed by a worker.
     * </pre>
     *
     * <code>EXECUTING = 3;</code>
     */
    EXECUTING(3),
    /**
     * <pre>
     * Finished execution.
     * </pre>
     *
     * <code>COMPLETED = 4;</code>
     */
    COMPLETED(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * Checking the result against the cache.
     * </pre>
     *
     * <code>CACHE_CHECK = 1;</code>
     */
    public static final int CACHE_CHECK_VALUE = 1;
    /**
     * <pre>
     * Currently idle, awaiting a free machine to execute.
     * </pre>
     *
     * <code>QUEUED = 2;</code>
     */
    public static final int QUEUED_VALUE = 2;
    /**
     * <pre>
     * Currently being executed by a worker.
     * </pre>
     *
     * <code>EXECUTING = 3;</code>
     */
    public static final int EXECUTING_VALUE = 3;
    /**
     * <pre>
     * Finished execution.
     * </pre>
     *
     * <code>COMPLETED = 4;</code>
     */
    public static final int COMPLETED_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Stage valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Stage forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return CACHE_CHECK;
        case 2: return QUEUED;
        case 3: return EXECUTING;
        case 4: return COMPLETED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Stage>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Stage> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Stage>() {
            public Stage findValueByNumber(int number) {
              return Stage.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.getDescriptor().getEnumTypes().get(0);
    }

    private static final Stage[] VALUES = values();

    public static Stage valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Stage(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage)
  }

  public static final int STAGE_FIELD_NUMBER = 1;
  private int stage_;
  /**
   * <code>.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage stage = 1;</code>
   * @return The enum numeric value on the wire for stage.
   */
  @java.lang.Override public int getStageValue() {
    return stage_;
  }
  /**
   * <code>.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage stage = 1;</code>
   * @return The stage.
   */
  @java.lang.Override public com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage getStage() {
    @SuppressWarnings("deprecation")
    com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage result = com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage.valueOf(stage_);
    return result == null ? com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage.UNRECOGNIZED : result;
  }

  public static final int ACTION_DIGEST_FIELD_NUMBER = 2;
  private com.google.devtools.remoteexecution.v1test.Digest actionDigest_;
  /**
   * <pre>
   * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
   * being executed.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
   * @return Whether the actionDigest field is set.
   */
  @java.lang.Override
  public boolean hasActionDigest() {
    return actionDigest_ != null;
  }
  /**
   * <pre>
   * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
   * being executed.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
   * @return The actionDigest.
   */
  @java.lang.Override
  public com.google.devtools.remoteexecution.v1test.Digest getActionDigest() {
    return actionDigest_ == null ? com.google.devtools.remoteexecution.v1test.Digest.getDefaultInstance() : actionDigest_;
  }
  /**
   * <pre>
   * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
   * being executed.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
   */
  @java.lang.Override
  public com.google.devtools.remoteexecution.v1test.DigestOrBuilder getActionDigestOrBuilder() {
    return getActionDigest();
  }

  public static final int STDOUT_STREAM_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object stdoutStreamName_;
  /**
   * <pre>
   * If set, the client can use this name with
   * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
   * standard output.
   * </pre>
   *
   * <code>string stdout_stream_name = 3;</code>
   * @return The stdoutStreamName.
   */
  @java.lang.Override
  public java.lang.String getStdoutStreamName() {
    java.lang.Object ref = stdoutStreamName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stdoutStreamName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * If set, the client can use this name with
   * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
   * standard output.
   * </pre>
   *
   * <code>string stdout_stream_name = 3;</code>
   * @return The bytes for stdoutStreamName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStdoutStreamNameBytes() {
    java.lang.Object ref = stdoutStreamName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stdoutStreamName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STDERR_STREAM_NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object stderrStreamName_;
  /**
   * <pre>
   * If set, the client can use this name with
   * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
   * standard error.
   * </pre>
   *
   * <code>string stderr_stream_name = 4;</code>
   * @return The stderrStreamName.
   */
  @java.lang.Override
  public java.lang.String getStderrStreamName() {
    java.lang.Object ref = stderrStreamName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stderrStreamName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * If set, the client can use this name with
   * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
   * standard error.
   * </pre>
   *
   * <code>string stderr_stream_name = 4;</code>
   * @return The bytes for stderrStreamName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStderrStreamNameBytes() {
    java.lang.Object ref = stderrStreamName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stderrStreamName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (stage_ != com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage.UNKNOWN.getNumber()) {
      output.writeEnum(1, stage_);
    }
    if (actionDigest_ != null) {
      output.writeMessage(2, getActionDigest());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stdoutStreamName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, stdoutStreamName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stderrStreamName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, stderrStreamName_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (stage_ != com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, stage_);
    }
    if (actionDigest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getActionDigest());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stdoutStreamName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, stdoutStreamName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stderrStreamName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, stderrStreamName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata)) {
      return super.equals(obj);
    }
    com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata other = (com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata) obj;

    if (stage_ != other.stage_) return false;
    if (hasActionDigest() != other.hasActionDigest()) return false;
    if (hasActionDigest()) {
      if (!getActionDigest()
          .equals(other.getActionDigest())) return false;
    }
    if (!getStdoutStreamName()
        .equals(other.getStdoutStreamName())) return false;
    if (!getStderrStreamName()
        .equals(other.getStderrStreamName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STAGE_FIELD_NUMBER;
    hash = (53 * hash) + stage_;
    if (hasActionDigest()) {
      hash = (37 * hash) + ACTION_DIGEST_FIELD_NUMBER;
      hash = (53 * hash) + getActionDigest().hashCode();
    }
    hash = (37 * hash) + STDOUT_STREAM_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getStdoutStreamName().hashCode();
    hash = (37 * hash) + STDERR_STREAM_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getStderrStreamName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Metadata about an ongoing
   * [execution][google.devtools.remoteexecution.v1test.Execution.Execute], which
   * will be contained in the [metadata
   * field][google.longrunning.Operation.response] of the
   * [Operation][google.longrunning.Operation].
   * </pre>
   *
   * Protobuf type {@code google.devtools.remoteexecution.v1test.ExecuteOperationMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.devtools.remoteexecution.v1test.ExecuteOperationMetadata)
      com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_ExecuteOperationMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_ExecuteOperationMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.class, com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Builder.class);
    }

    // Construct using com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      stage_ = 0;

      if (actionDigestBuilder_ == null) {
        actionDigest_ = null;
      } else {
        actionDigest_ = null;
        actionDigestBuilder_ = null;
      }
      stdoutStreamName_ = "";

      stderrStreamName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_ExecuteOperationMetadata_descriptor;
    }

    @java.lang.Override
    public com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata getDefaultInstanceForType() {
      return com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata build() {
      com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata buildPartial() {
      com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata result = new com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata(this);
      result.stage_ = stage_;
      if (actionDigestBuilder_ == null) {
        result.actionDigest_ = actionDigest_;
      } else {
        result.actionDigest_ = actionDigestBuilder_.build();
      }
      result.stdoutStreamName_ = stdoutStreamName_;
      result.stderrStreamName_ = stderrStreamName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata) {
        return mergeFrom((com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata other) {
      if (other == com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.getDefaultInstance()) return this;
      if (other.stage_ != 0) {
        setStageValue(other.getStageValue());
      }
      if (other.hasActionDigest()) {
        mergeActionDigest(other.getActionDigest());
      }
      if (!other.getStdoutStreamName().isEmpty()) {
        stdoutStreamName_ = other.stdoutStreamName_;
        onChanged();
      }
      if (!other.getStderrStreamName().isEmpty()) {
        stderrStreamName_ = other.stderrStreamName_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              stage_ = input.readEnum();

              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getActionDigestFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 18
            case 26: {
              stdoutStreamName_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              stderrStreamName_ = input.readStringRequireUtf8();

              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int stage_ = 0;
    /**
     * <code>.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage stage = 1;</code>
     * @return The enum numeric value on the wire for stage.
     */
    @java.lang.Override public int getStageValue() {
      return stage_;
    }
    /**
     * <code>.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage stage = 1;</code>
     * @param value The enum numeric value on the wire for stage to set.
     * @return This builder for chaining.
     */
    public Builder setStageValue(int value) {
      
      stage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage stage = 1;</code>
     * @return The stage.
     */
    @java.lang.Override
    public com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage getStage() {
      @SuppressWarnings("deprecation")
      com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage result = com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage.valueOf(stage_);
      return result == null ? com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage.UNRECOGNIZED : result;
    }
    /**
     * <code>.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage stage = 1;</code>
     * @param value The stage to set.
     * @return This builder for chaining.
     */
    public Builder setStage(com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      stage_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata.Stage stage = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStage() {
      
      stage_ = 0;
      onChanged();
      return this;
    }

    private com.google.devtools.remoteexecution.v1test.Digest actionDigest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.remoteexecution.v1test.Digest, com.google.devtools.remoteexecution.v1test.Digest.Builder, com.google.devtools.remoteexecution.v1test.DigestOrBuilder> actionDigestBuilder_;
    /**
     * <pre>
     * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
     * being executed.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
     * @return Whether the actionDigest field is set.
     */
    public boolean hasActionDigest() {
      return actionDigestBuilder_ != null || actionDigest_ != null;
    }
    /**
     * <pre>
     * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
     * being executed.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
     * @return The actionDigest.
     */
    public com.google.devtools.remoteexecution.v1test.Digest getActionDigest() {
      if (actionDigestBuilder_ == null) {
        return actionDigest_ == null ? com.google.devtools.remoteexecution.v1test.Digest.getDefaultInstance() : actionDigest_;
      } else {
        return actionDigestBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
     * being executed.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
     */
    public Builder setActionDigest(com.google.devtools.remoteexecution.v1test.Digest value) {
      if (actionDigestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        actionDigest_ = value;
        onChanged();
      } else {
        actionDigestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
     * being executed.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
     */
    public Builder setActionDigest(
        com.google.devtools.remoteexecution.v1test.Digest.Builder builderForValue) {
      if (actionDigestBuilder_ == null) {
        actionDigest_ = builderForValue.build();
        onChanged();
      } else {
        actionDigestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
     * being executed.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
     */
    public Builder mergeActionDigest(com.google.devtools.remoteexecution.v1test.Digest value) {
      if (actionDigestBuilder_ == null) {
        if (actionDigest_ != null) {
          actionDigest_ =
            com.google.devtools.remoteexecution.v1test.Digest.newBuilder(actionDigest_).mergeFrom(value).buildPartial();
        } else {
          actionDigest_ = value;
        }
        onChanged();
      } else {
        actionDigestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
     * being executed.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
     */
    public Builder clearActionDigest() {
      if (actionDigestBuilder_ == null) {
        actionDigest_ = null;
        onChanged();
      } else {
        actionDigest_ = null;
        actionDigestBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
     * being executed.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
     */
    public com.google.devtools.remoteexecution.v1test.Digest.Builder getActionDigestBuilder() {
      
      onChanged();
      return getActionDigestFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
     * being executed.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
     */
    public com.google.devtools.remoteexecution.v1test.DigestOrBuilder getActionDigestOrBuilder() {
      if (actionDigestBuilder_ != null) {
        return actionDigestBuilder_.getMessageOrBuilder();
      } else {
        return actionDigest_ == null ?
            com.google.devtools.remoteexecution.v1test.Digest.getDefaultInstance() : actionDigest_;
      }
    }
    /**
     * <pre>
     * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
     * being executed.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.remoteexecution.v1test.Digest, com.google.devtools.remoteexecution.v1test.Digest.Builder, com.google.devtools.remoteexecution.v1test.DigestOrBuilder> 
        getActionDigestFieldBuilder() {
      if (actionDigestBuilder_ == null) {
        actionDigestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.devtools.remoteexecution.v1test.Digest, com.google.devtools.remoteexecution.v1test.Digest.Builder, com.google.devtools.remoteexecution.v1test.DigestOrBuilder>(
                getActionDigest(),
                getParentForChildren(),
                isClean());
        actionDigest_ = null;
      }
      return actionDigestBuilder_;
    }

    private java.lang.Object stdoutStreamName_ = "";
    /**
     * <pre>
     * If set, the client can use this name with
     * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
     * standard output.
     * </pre>
     *
     * <code>string stdout_stream_name = 3;</code>
     * @return The stdoutStreamName.
     */
    public java.lang.String getStdoutStreamName() {
      java.lang.Object ref = stdoutStreamName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stdoutStreamName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * If set, the client can use this name with
     * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
     * standard output.
     * </pre>
     *
     * <code>string stdout_stream_name = 3;</code>
     * @return The bytes for stdoutStreamName.
     */
    public com.google.protobuf.ByteString
        getStdoutStreamNameBytes() {
      java.lang.Object ref = stdoutStreamName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stdoutStreamName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * If set, the client can use this name with
     * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
     * standard output.
     * </pre>
     *
     * <code>string stdout_stream_name = 3;</code>
     * @param value The stdoutStreamName to set.
     * @return This builder for chaining.
     */
    public Builder setStdoutStreamName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stdoutStreamName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If set, the client can use this name with
     * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
     * standard output.
     * </pre>
     *
     * <code>string stdout_stream_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStdoutStreamName() {
      
      stdoutStreamName_ = getDefaultInstance().getStdoutStreamName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If set, the client can use this name with
     * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
     * standard output.
     * </pre>
     *
     * <code>string stdout_stream_name = 3;</code>
     * @param value The bytes for stdoutStreamName to set.
     * @return This builder for chaining.
     */
    public Builder setStdoutStreamNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stdoutStreamName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object stderrStreamName_ = "";
    /**
     * <pre>
     * If set, the client can use this name with
     * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
     * standard error.
     * </pre>
     *
     * <code>string stderr_stream_name = 4;</code>
     * @return The stderrStreamName.
     */
    public java.lang.String getStderrStreamName() {
      java.lang.Object ref = stderrStreamName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stderrStreamName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * If set, the client can use this name with
     * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
     * standard error.
     * </pre>
     *
     * <code>string stderr_stream_name = 4;</code>
     * @return The bytes for stderrStreamName.
     */
    public com.google.protobuf.ByteString
        getStderrStreamNameBytes() {
      java.lang.Object ref = stderrStreamName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stderrStreamName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * If set, the client can use this name with
     * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
     * standard error.
     * </pre>
     *
     * <code>string stderr_stream_name = 4;</code>
     * @param value The stderrStreamName to set.
     * @return This builder for chaining.
     */
    public Builder setStderrStreamName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stderrStreamName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If set, the client can use this name with
     * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
     * standard error.
     * </pre>
     *
     * <code>string stderr_stream_name = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStderrStreamName() {
      
      stderrStreamName_ = getDefaultInstance().getStderrStreamName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If set, the client can use this name with
     * [ByteStream.Read][google.bytestream.ByteStream.Read] to stream the
     * standard error.
     * </pre>
     *
     * <code>string stderr_stream_name = 4;</code>
     * @param value The bytes for stderrStreamName to set.
     * @return This builder for chaining.
     */
    public Builder setStderrStreamNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stderrStreamName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.devtools.remoteexecution.v1test.ExecuteOperationMetadata)
  }

  // @@protoc_insertion_point(class_scope:google.devtools.remoteexecution.v1test.ExecuteOperationMetadata)
  private static final com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata();
  }

  public static com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecuteOperationMetadata>
      PARSER = new com.google.protobuf.AbstractParser<ExecuteOperationMetadata>() {
    @java.lang.Override
    public ExecuteOperationMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExecuteOperationMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecuteOperationMetadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.devtools.remoteexecution.v1test.ExecuteOperationMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

