// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/remoteexecution/v1test/remote_execution.proto

package com.google.devtools.remoteexecution.v1test;

/**
 * <pre>
 * A `Tree` contains all the
 * [Directory][google.devtools.remoteexecution.v1test.Directory] protos in a
 * single directory Merkle tree, compressed into one message.
 * </pre>
 *
 * Protobuf type {@code google.devtools.remoteexecution.v1test.Tree}
 */
public final class Tree extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.devtools.remoteexecution.v1test.Tree)
    TreeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Tree.newBuilder() to construct.
  private Tree(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Tree() {
    children_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Tree();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_Tree_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_Tree_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.devtools.remoteexecution.v1test.Tree.class, com.google.devtools.remoteexecution.v1test.Tree.Builder.class);
  }

  public static final int ROOT_FIELD_NUMBER = 1;
  private com.google.devtools.remoteexecution.v1test.Directory root_;
  /**
   * <pre>
   * The root directory in the tree.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Directory root = 1;</code>
   * @return Whether the root field is set.
   */
  @java.lang.Override
  public boolean hasRoot() {
    return root_ != null;
  }
  /**
   * <pre>
   * The root directory in the tree.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Directory root = 1;</code>
   * @return The root.
   */
  @java.lang.Override
  public com.google.devtools.remoteexecution.v1test.Directory getRoot() {
    return root_ == null ? com.google.devtools.remoteexecution.v1test.Directory.getDefaultInstance() : root_;
  }
  /**
   * <pre>
   * The root directory in the tree.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Directory root = 1;</code>
   */
  @java.lang.Override
  public com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder getRootOrBuilder() {
    return getRoot();
  }

  public static final int CHILDREN_FIELD_NUMBER = 2;
  private java.util.List<com.google.devtools.remoteexecution.v1test.Directory> children_;
  /**
   * <pre>
   * All the child directories: the directories referred to by the root and,
   * recursively, all its children. In order to reconstruct the directory tree,
   * the client must take the digests of each of the child directories and then
   * build up a tree starting from the `root`.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.devtools.remoteexecution.v1test.Directory> getChildrenList() {
    return children_;
  }
  /**
   * <pre>
   * All the child directories: the directories referred to by the root and,
   * recursively, all its children. In order to reconstruct the directory tree,
   * the client must take the digests of each of the child directories and then
   * build up a tree starting from the `root`.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder> 
      getChildrenOrBuilderList() {
    return children_;
  }
  /**
   * <pre>
   * All the child directories: the directories referred to by the root and,
   * recursively, all its children. In order to reconstruct the directory tree,
   * the client must take the digests of each of the child directories and then
   * build up a tree starting from the `root`.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
   */
  @java.lang.Override
  public int getChildrenCount() {
    return children_.size();
  }
  /**
   * <pre>
   * All the child directories: the directories referred to by the root and,
   * recursively, all its children. In order to reconstruct the directory tree,
   * the client must take the digests of each of the child directories and then
   * build up a tree starting from the `root`.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
   */
  @java.lang.Override
  public com.google.devtools.remoteexecution.v1test.Directory getChildren(int index) {
    return children_.get(index);
  }
  /**
   * <pre>
   * All the child directories: the directories referred to by the root and,
   * recursively, all its children. In order to reconstruct the directory tree,
   * the client must take the digests of each of the child directories and then
   * build up a tree starting from the `root`.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
   */
  @java.lang.Override
  public com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder getChildrenOrBuilder(
      int index) {
    return children_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (root_ != null) {
      output.writeMessage(1, getRoot());
    }
    for (int i = 0; i < children_.size(); i++) {
      output.writeMessage(2, children_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (root_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRoot());
    }
    for (int i = 0; i < children_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, children_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.devtools.remoteexecution.v1test.Tree)) {
      return super.equals(obj);
    }
    com.google.devtools.remoteexecution.v1test.Tree other = (com.google.devtools.remoteexecution.v1test.Tree) obj;

    if (hasRoot() != other.hasRoot()) return false;
    if (hasRoot()) {
      if (!getRoot()
          .equals(other.getRoot())) return false;
    }
    if (!getChildrenList()
        .equals(other.getChildrenList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRoot()) {
      hash = (37 * hash) + ROOT_FIELD_NUMBER;
      hash = (53 * hash) + getRoot().hashCode();
    }
    if (getChildrenCount() > 0) {
      hash = (37 * hash) + CHILDREN_FIELD_NUMBER;
      hash = (53 * hash) + getChildrenList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.devtools.remoteexecution.v1test.Tree parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.remoteexecution.v1test.Tree parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.Tree parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.remoteexecution.v1test.Tree parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.Tree parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.remoteexecution.v1test.Tree parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.Tree parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.remoteexecution.v1test.Tree parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.Tree parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.devtools.remoteexecution.v1test.Tree parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.Tree parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.remoteexecution.v1test.Tree parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.devtools.remoteexecution.v1test.Tree prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A `Tree` contains all the
   * [Directory][google.devtools.remoteexecution.v1test.Directory] protos in a
   * single directory Merkle tree, compressed into one message.
   * </pre>
   *
   * Protobuf type {@code google.devtools.remoteexecution.v1test.Tree}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.devtools.remoteexecution.v1test.Tree)
      com.google.devtools.remoteexecution.v1test.TreeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_Tree_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_Tree_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.devtools.remoteexecution.v1test.Tree.class, com.google.devtools.remoteexecution.v1test.Tree.Builder.class);
    }

    // Construct using com.google.devtools.remoteexecution.v1test.Tree.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (rootBuilder_ == null) {
        root_ = null;
      } else {
        root_ = null;
        rootBuilder_ = null;
      }
      if (childrenBuilder_ == null) {
        children_ = java.util.Collections.emptyList();
      } else {
        children_ = null;
        childrenBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_Tree_descriptor;
    }

    @java.lang.Override
    public com.google.devtools.remoteexecution.v1test.Tree getDefaultInstanceForType() {
      return com.google.devtools.remoteexecution.v1test.Tree.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.devtools.remoteexecution.v1test.Tree build() {
      com.google.devtools.remoteexecution.v1test.Tree result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.devtools.remoteexecution.v1test.Tree buildPartial() {
      com.google.devtools.remoteexecution.v1test.Tree result = new com.google.devtools.remoteexecution.v1test.Tree(this);
      int from_bitField0_ = bitField0_;
      if (rootBuilder_ == null) {
        result.root_ = root_;
      } else {
        result.root_ = rootBuilder_.build();
      }
      if (childrenBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          children_ = java.util.Collections.unmodifiableList(children_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.children_ = children_;
      } else {
        result.children_ = childrenBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.devtools.remoteexecution.v1test.Tree) {
        return mergeFrom((com.google.devtools.remoteexecution.v1test.Tree)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.devtools.remoteexecution.v1test.Tree other) {
      if (other == com.google.devtools.remoteexecution.v1test.Tree.getDefaultInstance()) return this;
      if (other.hasRoot()) {
        mergeRoot(other.getRoot());
      }
      if (childrenBuilder_ == null) {
        if (!other.children_.isEmpty()) {
          if (children_.isEmpty()) {
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChildrenIsMutable();
            children_.addAll(other.children_);
          }
          onChanged();
        }
      } else {
        if (!other.children_.isEmpty()) {
          if (childrenBuilder_.isEmpty()) {
            childrenBuilder_.dispose();
            childrenBuilder_ = null;
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000001);
            childrenBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getChildrenFieldBuilder() : null;
          } else {
            childrenBuilder_.addAllMessages(other.children_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getRootFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            case 18: {
              com.google.devtools.remoteexecution.v1test.Directory m =
                  input.readMessage(
                      com.google.devtools.remoteexecution.v1test.Directory.parser(),
                      extensionRegistry);
              if (childrenBuilder_ == null) {
                ensureChildrenIsMutable();
                children_.add(m);
              } else {
                childrenBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.devtools.remoteexecution.v1test.Directory root_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.remoteexecution.v1test.Directory, com.google.devtools.remoteexecution.v1test.Directory.Builder, com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder> rootBuilder_;
    /**
     * <pre>
     * The root directory in the tree.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Directory root = 1;</code>
     * @return Whether the root field is set.
     */
    public boolean hasRoot() {
      return rootBuilder_ != null || root_ != null;
    }
    /**
     * <pre>
     * The root directory in the tree.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Directory root = 1;</code>
     * @return The root.
     */
    public com.google.devtools.remoteexecution.v1test.Directory getRoot() {
      if (rootBuilder_ == null) {
        return root_ == null ? com.google.devtools.remoteexecution.v1test.Directory.getDefaultInstance() : root_;
      } else {
        return rootBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The root directory in the tree.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Directory root = 1;</code>
     */
    public Builder setRoot(com.google.devtools.remoteexecution.v1test.Directory value) {
      if (rootBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        root_ = value;
        onChanged();
      } else {
        rootBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The root directory in the tree.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Directory root = 1;</code>
     */
    public Builder setRoot(
        com.google.devtools.remoteexecution.v1test.Directory.Builder builderForValue) {
      if (rootBuilder_ == null) {
        root_ = builderForValue.build();
        onChanged();
      } else {
        rootBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The root directory in the tree.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Directory root = 1;</code>
     */
    public Builder mergeRoot(com.google.devtools.remoteexecution.v1test.Directory value) {
      if (rootBuilder_ == null) {
        if (root_ != null) {
          root_ =
            com.google.devtools.remoteexecution.v1test.Directory.newBuilder(root_).mergeFrom(value).buildPartial();
        } else {
          root_ = value;
        }
        onChanged();
      } else {
        rootBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The root directory in the tree.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Directory root = 1;</code>
     */
    public Builder clearRoot() {
      if (rootBuilder_ == null) {
        root_ = null;
        onChanged();
      } else {
        root_ = null;
        rootBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The root directory in the tree.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Directory root = 1;</code>
     */
    public com.google.devtools.remoteexecution.v1test.Directory.Builder getRootBuilder() {
      
      onChanged();
      return getRootFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The root directory in the tree.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Directory root = 1;</code>
     */
    public com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder getRootOrBuilder() {
      if (rootBuilder_ != null) {
        return rootBuilder_.getMessageOrBuilder();
      } else {
        return root_ == null ?
            com.google.devtools.remoteexecution.v1test.Directory.getDefaultInstance() : root_;
      }
    }
    /**
     * <pre>
     * The root directory in the tree.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Directory root = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.remoteexecution.v1test.Directory, com.google.devtools.remoteexecution.v1test.Directory.Builder, com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder> 
        getRootFieldBuilder() {
      if (rootBuilder_ == null) {
        rootBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.devtools.remoteexecution.v1test.Directory, com.google.devtools.remoteexecution.v1test.Directory.Builder, com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder>(
                getRoot(),
                getParentForChildren(),
                isClean());
        root_ = null;
      }
      return rootBuilder_;
    }

    private java.util.List<com.google.devtools.remoteexecution.v1test.Directory> children_ =
      java.util.Collections.emptyList();
    private void ensureChildrenIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        children_ = new java.util.ArrayList<com.google.devtools.remoteexecution.v1test.Directory>(children_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.devtools.remoteexecution.v1test.Directory, com.google.devtools.remoteexecution.v1test.Directory.Builder, com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder> childrenBuilder_;

    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public java.util.List<com.google.devtools.remoteexecution.v1test.Directory> getChildrenList() {
      if (childrenBuilder_ == null) {
        return java.util.Collections.unmodifiableList(children_);
      } else {
        return childrenBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public int getChildrenCount() {
      if (childrenBuilder_ == null) {
        return children_.size();
      } else {
        return childrenBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public com.google.devtools.remoteexecution.v1test.Directory getChildren(int index) {
      if (childrenBuilder_ == null) {
        return children_.get(index);
      } else {
        return childrenBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public Builder setChildren(
        int index, com.google.devtools.remoteexecution.v1test.Directory value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.set(index, value);
        onChanged();
      } else {
        childrenBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public Builder setChildren(
        int index, com.google.devtools.remoteexecution.v1test.Directory.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.set(index, builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public Builder addChildren(com.google.devtools.remoteexecution.v1test.Directory value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.add(value);
        onChanged();
      } else {
        childrenBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public Builder addChildren(
        int index, com.google.devtools.remoteexecution.v1test.Directory value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.add(index, value);
        onChanged();
      } else {
        childrenBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public Builder addChildren(
        com.google.devtools.remoteexecution.v1test.Directory.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.add(builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public Builder addChildren(
        int index, com.google.devtools.remoteexecution.v1test.Directory.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.add(index, builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public Builder addAllChildren(
        java.lang.Iterable<? extends com.google.devtools.remoteexecution.v1test.Directory> values) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, children_);
        onChanged();
      } else {
        childrenBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public Builder clearChildren() {
      if (childrenBuilder_ == null) {
        children_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        childrenBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public Builder removeChildren(int index) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.remove(index);
        onChanged();
      } else {
        childrenBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public com.google.devtools.remoteexecution.v1test.Directory.Builder getChildrenBuilder(
        int index) {
      return getChildrenFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder getChildrenOrBuilder(
        int index) {
      if (childrenBuilder_ == null) {
        return children_.get(index);  } else {
        return childrenBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public java.util.List<? extends com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder> 
         getChildrenOrBuilderList() {
      if (childrenBuilder_ != null) {
        return childrenBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(children_);
      }
    }
    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public com.google.devtools.remoteexecution.v1test.Directory.Builder addChildrenBuilder() {
      return getChildrenFieldBuilder().addBuilder(
          com.google.devtools.remoteexecution.v1test.Directory.getDefaultInstance());
    }
    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public com.google.devtools.remoteexecution.v1test.Directory.Builder addChildrenBuilder(
        int index) {
      return getChildrenFieldBuilder().addBuilder(
          index, com.google.devtools.remoteexecution.v1test.Directory.getDefaultInstance());
    }
    /**
     * <pre>
     * All the child directories: the directories referred to by the root and,
     * recursively, all its children. In order to reconstruct the directory tree,
     * the client must take the digests of each of the child directories and then
     * build up a tree starting from the `root`.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory children = 2;</code>
     */
    public java.util.List<com.google.devtools.remoteexecution.v1test.Directory.Builder> 
         getChildrenBuilderList() {
      return getChildrenFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.devtools.remoteexecution.v1test.Directory, com.google.devtools.remoteexecution.v1test.Directory.Builder, com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder> 
        getChildrenFieldBuilder() {
      if (childrenBuilder_ == null) {
        childrenBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.devtools.remoteexecution.v1test.Directory, com.google.devtools.remoteexecution.v1test.Directory.Builder, com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder>(
                children_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        children_ = null;
      }
      return childrenBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.devtools.remoteexecution.v1test.Tree)
  }

  // @@protoc_insertion_point(class_scope:google.devtools.remoteexecution.v1test.Tree)
  private static final com.google.devtools.remoteexecution.v1test.Tree DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.devtools.remoteexecution.v1test.Tree();
  }

  public static com.google.devtools.remoteexecution.v1test.Tree getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Tree>
      PARSER = new com.google.protobuf.AbstractParser<Tree>() {
    @java.lang.Override
    public Tree parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Tree> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Tree> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.devtools.remoteexecution.v1test.Tree getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

